### ISSUE TITLE
Database connector improvement ideas

### ISSUE THREAD

**Issue by DaMaMs** [wakdev/slash-cms#13]
Le DB connector hérite de dbconfig.

Le DB connector est basé sur le design pattern Singleton : Quoique tu fasses, le DB connector ouverte n'ai instancier qu'une seul fois. Ça évite les connections massive pour mauvaise gestion des accès à la base. Je doit avoir des modèle qui traînent. http://fr.wikipedia.org/wiki/Singleton_(patron_de_conception)... J'avais utiliser ça pour mon mini FrameWork MVC sur https://e-bp2l.net/

Sur le Singleton : http://truffo.fr/2009/08/design-pattern-singleton/
http://smeric.developpez.com/java/uml/singleton/

**Comment by wakdev** [comment]
Oui bonne idée, même si le système n'instancie qu'une seule fois la classe d’abstraction bdd, cela éviterai effectivement une mauvaise utilisation. J'ai implémenté les connector il n'y a pas très longtemps. Je prends note et intègre ça dès que possible. :)

**Comment by wakdev** [comment]
Singleton en place : https://github.com/wakdev/slash-cms/commit/d219135f577e894e032db860d87ffe1dca72815c
