### ISSUE TITLE
Slash est compatible avec quelle versions de PHP ?

### ISSUE THREAD

**Issue by DaMaMs** [wakdev/slash-cms#24]
J'ai une idée d’implémentation élégante de la Class sl_config mais je crois que c'est très PHP 5.3.0;

Faire des
$config::cle(valeur);
pour définir les variable de configuration.
et des 
$valeur = $config::cle();
pour récupérer les valeurs de configurations

avec les supers méthodes
public function __call($name, $arguments) - PHP 5.1.0
public static function __callStatic($name, $arguments) - PHP 5.3.0

**Comment by wakdev** [comment]
Oui, compatible (en théorie).
Par contre, une méthode statique pour modifier une valeur, ce n'est pas un peu bizarre ?  $config::cle(valeur)

**Comment by DaMaMs** [comment]
heu je t'avoue que j'avais fait un truc du genre la... la j'ai posté sans vraiment réfléchir...  C’était a base de singleton et de super méthode ! Me rappelle plus mais c'était sympa de configurer à base de $config::montruc ou ->montruc je sais plus et je t'avoue que je suis trop naze pour réfléchir...

**Comment by DaMaMs** [comment]
J'avais écrit un super mini langage de template extensible a base classe et de preg_replace preg_replace_callback c’était la belle époque avant que je craque je format le disque sur lequel j'avais le backup de ma clé que j'avais vidé en me disant que toute façon j'avais le backup sur le disque ! Bref ! j'men moque j'ai remplacer le codage PHP par le parternage et mon petit Arthur il ROX plus que mille millard de CMS ! Dommage pour les belles lignes de codes ! Maintenant je kiffe faire des petit humain ;)

**Comment by wakdev** [comment]
Il est bogué Arthur ^^
