### ISSUE TITLE
TODO : Intégration de KCFinder dans CKEditor

### ISSUE THREAD

**Issue by wakdev** [wakdev/slash-cms#28]
Remplacement de CKFinder par l'outil open source : KCFinder
http://kcfinder.sunhater.com

Une intégration "standalone" est déjà en place dans le module sla_medias
https://github.com/wakdev/slash-cms/commit/2f2cd9968a93f11820909c0189cdc956b4e5889a

**Comment by wakdev** [comment]
Intégration terminé : https://github.com/wakdev/slash-cms/commit/958bc1e21e017656c64217c402c839fd476805b3
Mais pas certain de la pertinence du $_SERVER["HTTP_HOST"]; voir ligne 102 : 
https://github.com/wakdev/slash-cms/blob/958bc1e21e017656c64217c402c839fd476805b3/core/plugins/kcfinder/config.php#L102

Votre avis sur ce point ?

**Comment by wakdev** [comment]
UP ?

**Comment by lowki** [comment]
J'ai testé un peu la variable, elle retourne bien le bon host, même si c'est un virtuel.
Par contre, faut-il coller /medias directement après? Si slash est installé dans un répertoire plus bas, ça ne fonctionnera pas.

**Comment by wakdev** [comment]
"Par contre, faut-il coller /medias directement après?"
J'ai pas compris ^^'

**Comment by lowki** [comment]
Si slash est accessible via domain.tld/slashcms/index.php, _sessionPath pointera vers domain.tld/medias.

**Comment by wakdev** [comment]
Ah bin oui, c'est un problème...
Eventuellement, on peux configurer le path dans le fichier de config $site_path = "slashcms/"

**Comment by lowki** [comment]
C'est à ça que je pensais.
