### ISSUE TITLE
INFO : Liste des développeurs & contributeurs

### ISSUE THREAD

**Issue by wakdev** [wakdev/slash-cms#53]
J'ai pensé que la moindre des choses serai de noter la liste des développeurs ayant contribué / participé au projet : https://github.com/wakdev/slash-cms#developers--contributors

Si vous souhaitez indiquer d'autres informations type site web ou autre, faites le moi savoir.

**Comment by lowki** [comment]
C'est bien aimable :)

**Comment by rbcreation** [comment]
:-)
