### ISSUE TITLE
BUG: ckeditor medias path is wrong when slash in subfolder

### ISSUE THREAD

**Issue by lowki** [wakdev/slash-cms#55]
For example slash is accessible via localhost/slash-cms/
Images are uploaded into the good folder, but the preview doesn't working.
The path is set to /media by default, either if it is set to media, it doesn't work too as it is relative to admin path.

**Comment by wakdev** [comment]
An idea ?

**Comment by lowki** [comment]
Grab the site_path config param.
And inject it [there ](http://docs.cksource.com/ckeditor_api/symbols/CKEDITOR.config.html#.baseHref)

**Comment by wakdev** [comment]
I had already added the parameter in the session here : https://github.com/wakdev/slash-cms/blob/master/admin/modules/sla_secure/controller.php#L81

**Comment by wakdev** [comment]
I tested and I do not see any problem ><
You just set the site_path parameter correctly.

**Comment by wakdev** [comment]
Have you try to turn on and off again ? ^^ (cf : IT Crowd)

**Comment by lowki** [comment]
I made tests and it seems to work.
But on one of my webserver, I have a weird bug, image URL is relative to server root path (ie. /var/www)
I asked ckeditor team for futher informations.

**Comment by wakdev** [comment]
I think you use internet explorer ^^

**Comment by lowki** [comment]
https://github.com/lowki/slash-cms/commit/47cd31bc0382585eadeba8093d2561f99b6974e8

**Comment by wakdev** [comment]
Ahah ^^
