### ISSUE TITLE
Todo - autoload

### ISSUE THREAD

**Issue by wakdev** [wakdev/slash-cms#6]
Mise en place de l'autoload sur les classes de fonctions.

**Comment by wakdev** [comment]
Done : https://github.com/wakdev/slash-cms/commit/dfd7c683fde05313aff504ccfa05e44ff2253217

**Comment by lowki** [comment]
Pourquoi ne pas l'implémenter directement dans le noyau pour l'ensemble du
CMS?

**Comment by wakdev** [comment]
Oui j'y ai pensé, je pense que je vais le faire prochainement, pour gérer correctement les erreurs de chargement des classes :)

**Comment by wakdev** [comment]
C'est fait :) 
https://github.com/wakdev/slash-cms/commit/b36552b8b0e096ca6536b9566ce5e771e1867505
