### ISSUE TITLE
BUG : Magic quote

### ISSUE THREAD

**Issue by wakdev** [wakdev/slash-cms#66]
Problème avec les méthodes escape si les magic quote sont déjà activées sur le serveur.

**Comment by wakdev** [comment]
Rajoute des anti-slash (cms) ^^

**Comment by wakdev** [comment]
Je vais ajouter quand j'aurai 5minutes une vérification avec http://php.net/manual/en/function.get-magic-quotes-gpc.php

**Comment by lowki** [comment]
C'est quand tu répond a ton propre commentaire que tu comprend que t'es un sacré geek :p 
Je rajouterais ça dans le setup.

**Comment by wakdev** [comment]
Lol, oui c'est certain... d'ailleurs, je n'arrive pas à reproduire le bug de mon mutualisé sur mon localhost.
Pas sur que cela vienne des magic quotes.

**Comment by wakdev** [comment]
Réglé : https://github.com/wakdev/slash-cms/commit/c5562916f55563a8dc6b6167f5761d3cd2c0560b
